[Protocol]
/dev/binderfs/binder = aidl2
/dev/binderfs/hwbinder = hidl
/dev/binderfs/vndbinder = hidl

[ServiceManager]
/dev/binderfs/binder = aidl2
/dev/binderfs/hwbinder = hidl
/dev/binderfs/vndbinder = hidl
