# Ofono config for Samsung SM-T225 (MT8768 LTE - Single SIM)

[Settings]
emptyPinQuery=false
radioPowerCycle=false
confirmRadioPowerOn=false
networkSelectionManual0=false
cellInfoIntervalShortMs=0
useDataProfiles=true
mmsDataProfileId=1001
rilRequestOnSetUdub=13

[ril_0]
# MT8768 Android 12 RIL: try radio@1.6 first
# If calls fail, change to radio@1.4
transport=binder:name=slot1;interface=radio@1.6
name=slot1
